name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: 3.0
commands:
  customitems:
    description: give a custom item to a player
    useage: /ci give <item name> [player name]
    aliases: [ci]