name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: 4.5
depend: [KnokkoCore]
commands:
  customitems:
    description: give a custom item to a player
    useage: /ci give <item name> [player name]
    aliases: [ci]